<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Check In-store Availability'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field quantity qty-product-buy">
            <div class="control">
				<span class="edit-qty minus" onclick="minusQty('qty')"><i class="fa fa-minus"></i></span>
				<input type="text" name="qty" id="qty" maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
				<span class="edit-qty plus" onclick="plusQty('qty')"><i class="fa fa-plus"></i></span>
            </div>
			<div class="qty-changer">
				<a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i></a>
				<a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i></a>
			</div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart btn btn-lg btn-primary add-to-bag"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
		<div class="clear"></div>
    </div>
</div>
<?php endif; ?>




<!-- <h1><?php //echo $_product->getProductUrl(); ?></h1> -->
<?php $_product = $this->getProduct();
      $sku = $_product->getSku();

?>
<h1><?php //echo $sku; ?></h1>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
        "#product_addtocart_form": {
        "Magento_Catalog/product/view/validation": {
        "radioCheckboxClosest": ".nested"
        }
        }
        }
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });

            jQuery('.ajaxcart-popup .close').click(function () {
                jQuery('.ajaxcart-popup').hide();
            });
        });
    </script>
<?php endif; ?>

<div class="ajaxcart-popup" id="ajaxcartProcessing">
    <div class="content">
        <span class="step processing"></span><?php echo __('Product') . ': ' . $_product->getName() . ' ' . __('are being added to cart ...'); ?>
        <div class="close"><?php echo __('x'); ?></div>
    </div>
</div>
