<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

	
	<em class="fa fa-times hidden-md hidden-lg"></em>
    <ul  class="container desktop-nav">
				<!-- data-mage-init='{"menu":{"responsive":true, "expanded":false, "position":{"my":"left top","at":"left bottom"}}}' -->
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
	
	<div class="mobile-nav d-hide">
		<?php echo $this->getChildHtml('mobile_nav');?>
	</div>
