<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
                <button
                    class="action-primary submit"
                    type="submit"
                    title="<?= $block->escapeHtmlAttr(__('Import Orders')) ?>">
                    <?= $block->escapeHtml(__('Import Orders')) ?>
                </button>
        </div>
    </div>
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
                <button
                    class="action-primary submit"
                    type="submit"
                    title="<?= $block->escapeHtmlAttr(__('Reset')) ?>">
                    <?= $block->escapeHtml(__('Reset')) ?>
                </button>
        </div>
    </div>
</div>
